# Reference channel configs.
# video_urls: manually curated list of top-performing video URLs per channel.
# Add URLs before running build_kb.py. Target ~20 per channel.

REFERENCE_CHANNELS: dict = {
    "johnny_harris": {
        "name": "Johnny Harris",
        "focus": "storytelling, emotional arc, host-driven documentary style",
        "video_urls": [
            "https://youtu.be/2r5eKpptixo",
            "https://youtu.be/tWxh2oS7Ays",
            "https://youtu.be/IwJzsE8CvzQ",
            "https://youtu.be/SrDEtSlqJC4",
            "https://youtu.be/VNZ0so0LCoM",
            "https://youtu.be/czQrU0OPIR8",
            "https://youtu.be/hrORwk_RZLM",
            "https://youtu.be/FQ4hvLqNfqo",
            "https://youtu.be/LJNtfyq3TDE",
            "https://youtu.be/9bPIaHg11mI",
            "https://youtu.be/Oz9zw7-_vhM",
            "https://youtu.be/wQSxY7TR6mI",
            "https://youtu.be/T-_HKFjxVl0",
            "https://youtu.be/WYQxG4KEzvo",
            "https://youtu.be/_wIOqHSsV9c",
            "https://youtu.be/aTMsfOcHiJg",
            "https://youtu.be/HBlZlmXyR5M",
            "https://youtu.be/YnOdULpV810",
            "https://youtu.be/AecFpnj383A",
            "https://youtu.be/UGzI-ABpy6k",
        ],
        "target_count": 20,
    },
    "wendover": {
        "name": "Wendover Productions",
        "focus": "research depth, information pacing, visual evidence",
        "video_urls": [
            "https://youtu.be/c0pS3Zx7Fc8",
            "https://youtu.be/GiBF6v5UAAE",
            "https://youtu.be/YJRqB1xtIxg",
            "https://youtu.be/BzB5xtGGsTc",
            "https://youtu.be/gdy0gBVWAzE",
            "https://youtu.be/b4wRdoWpw0w",
            "https://youtu.be/069y1MpOkQY",
            "https://youtu.be/5-QejUTDCWw",
            "https://youtu.be/MP1OAm7Pzps",
            "https://youtu.be/zQV_DKQkT8o",
            "https://youtu.be/P-b4SUOfn_4",
            "https://youtu.be/v3C_5bsdQWg",
            "https://youtu.be/0JDoll8OEFE",
            "https://youtu.be/b1JlYZQG3lI",
            "https://youtu.be/y3qfeoqErtY",
            "https://youtu.be/n1QEj09Pe6k",
            "https://youtu.be/oL0umpPPe-8",
            "https://youtu.be/ggUduBmvQ_4",
            "https://youtu.be/6OLVFa8YRfM",
            "https://youtu.be/5SDUm1bx7Zc",
        ],
        "target_count": 20,
    },
    "kurzgesagt": {
        "name": "Kurzgesagt",
        "focus": "hook mastery, script structure, retention engineering",
        "video_urls": [
            "https://youtu.be/BtN-goy9VOY",
            "https://youtu.be/zQGOcOUBi6s",
            "https://youtu.be/9tbxDgcv74c",
            "https://youtu.be/h6fcK_fRYaI",
            "https://youtu.be/3mnSDifDSxQ",
            "https://youtu.be/sNhhvQGsMEc",
            "https://youtu.be/YI3tsmFsrOg",
            "https://youtu.be/JyECrGp-Sw8",
            "https://youtu.be/0FH9cgRhQ-k",
            "https://youtu.be/yWO-cvGETRQ",
            "https://youtu.be/jAhjPd4uNFY",
            "https://youtu.be/ulCdoCfw-bY",
            "https://youtu.be/5iPH-br_eJQ",
            "https://youtu.be/4_aOIA-vyBo",
            "https://youtu.be/n3Xv_g3g-mA",
            "https://youtu.be/7_e0CA_nhaE",
            "https://youtu.be/UjtOGPJ0URM",
            "https://youtu.be/e-P5IFTqB98",
            "https://youtu.be/1AElONvi9WQ",
            "https://youtu.be/Da-2h2B4faU",
        ],
        "target_count": 20,
    },
    "veritasium": {
        "name": "Veritasium",
        "focus": "curiosity-gap hooks, surprise reveals, viewer psychology",
        "video_urls": [
            "https://youtu.be/uxPdPpi5W4o",
            "https://youtu.be/4Wrc4fHSCpw",
            "https://youtu.be/AeJ9q45PfD0",
            "https://youtu.be/2OSrvzNW9FE",
            "https://youtu.be/AF8d72mA41M",
            "https://youtu.be/094y1Z2wpJg",
            "https://youtu.be/IV3dnLzthDA",
            "https://youtu.be/pir_muTzYM8",
            "https://youtu.be/GcdB5bFwio4",
            "https://youtu.be/ZMByI4s-D-Y",
            "https://youtu.be/OxGsU8oIWjY",
            "https://youtu.be/qevIIQHrJZg",
            "https://youtu.be/GeyDf4ooPdo",
            "https://youtu.be/SC2eSujzrUY",
            "https://youtu.be/6akmv1bsz1M",
            "https://youtu.be/BZbChKzedEk",
            "https://youtu.be/mXVGIb3bzHI",
            "https://youtu.be/HeQX2HjkcNo",
            "https://youtu.be/DxL2HoqLbyA",
            "https://youtu.be/t-_VPRCtiUg",
        ],
        "target_count": 20,
    },
    "reallifelore": {
        "name": "RealLifeLore",
        "focus": "geographic/analytical framing, b-roll discipline",
        "video_urls": [
            "https://youtu.be/GE-lAftuQgc",
            "https://youtu.be/E39GIysMevQ",
            "https://youtu.be/Iy7NzjCmUf0",
            "https://youtu.be/hOFRbjjjwCE",
            "https://youtu.be/lPNrtjboISg",
            "https://youtu.be/9mVRc80vhhQ",
            "https://youtu.be/If61baWF4GE",
            "https://youtu.be/OQ9zng2S810",
            "https://youtu.be/jlX7tl1QvJs",
            "https://youtu.be/si9Phc9ArpU",
            "https://youtu.be/3bifbg12u28",
            "https://youtu.be/fs1CIrwg5zU",
            "https://youtu.be/ap4eVlcYLww",
            "https://youtu.be/TnB_8Zm9lPk",
            "https://youtu.be/L6tJ-mvhznU",
            "https://youtu.be/7oaGUg7ik_c",
            "https://youtu.be/RqrrWejHHeI",
            "https://youtu.be/ZbhqHCqjoZ0",
            "https://youtu.be/UbffuGZHeR0",
            "https://youtu.be/Iibs7buNwxQ",
        ],
        "target_count": 20,
    },
}

CHANNEL_PROFILES: dict = {
    "predictive_echoes": {
        "domain": "geopolitics, technology, future trends",
        "tone": "analytical, slightly urgent, forward-looking",
        "arc_template": "trend_identification → implication → future_scenario",
        "visual_style": "data-heavy, news footage, maps, graphs",
        "north_star": "make the viewer see something coming they hadn't noticed",
        "reference_channels": ["wendover", "reallifelore"],
        "avg_length_min": 10,
    },
    "incentives_lab": {
        "domain": "economics, human behavior, incentive structures",
        "tone": "curious, slightly provocative, Munger-esque",
        "arc_template": "surface_reality → hidden_incentive → reframe",
        "visual_style": "human-focused, institutional, everyday scenes",
        "north_star": "make the viewer distrust something they trusted before",
        "reference_channels": ["johnny_harris", "kurzgesagt"],
        "avg_length_min": 10,  # canonical: 10 min target (matches PRODUCTION_CHANNELS)
    },
}

PRODUCTION_CHANNELS: dict = {
    "incentiveslab": {
        "name": "IncentivesLab",
        "handle": "@IncentivesLab",
        "domain": "economics, human behavior, incentive structures, mental models",
        "tone": "curious, slightly provocative, Munger-esque, educational",
        "arc_template": "surface_reality → hidden_incentive → reframe",
        "visual_style": "real footage, human-focused, institutional, everyday scenes",
        "north_star": "make the viewer distrust something they trusted before",
        "channel_north_star": "Create a video so compelling that a viewer who stumbled on it accidentally can't stop watching — and shares it before it ends.",
        "reference_channels": ["johnny_harris", "kurzgesagt"],
        "avg_length_min": 10,
        "core_thesis": "Show me the incentive and I'll show you the outcome",
    }
}
